{
 "title": "Gunicorn Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gunicorn_requests" }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_response_code{app=\"$app_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(gunicorn_requests{app=\"$app_name\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gunicorn_request_duration_sum/ gunicorn_request_duration_count",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_requests{app=\"service\"}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_response_code{app=\"service\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(gunicorn_requests{app=\"service\"}[1m])"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_requests{app=\"modelling-cpu\"}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gunicorn_response_code{app=\"modelling-cpu\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "rate(gunicorn_requests{app=\"modelling-cpu\"}[1m])"
    }
   ]
  }
 ]
}